# Generated by Django 3.0.4 on 2020-03-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_auto_20200309_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='module_code',
        ),
        migrations.RemoveField(
            model_name='module',
            name='module_name',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='professor_id',
        ),
        migrations.AddField(
            model_name='module',
            name='mod_code',
            field=models.CharField(default='Module Code', max_length=3),
        ),
        migrations.AddField(
            model_name='module',
            name='name',
            field=models.CharField(default='Module Name', max_length=100),
        ),
        migrations.AddField(
            model_name='professor',
            name='prof_id',
            field=models.CharField(default='', max_length=3, verbose_name='ID'),
        ),
    ]
