# Generated by Django 3.0.4 on 2020-03-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_auto_20200309_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='mod_code',
            field=models.CharField(default='', max_length=3, verbose_name='Module Code'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Module Name'),
        ),
    ]
